/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package audioTactileMap;

import java.awt.event.WindowEvent;

/**
 *
 * @author Administrator
 */
public class AudioSettings extends javax.swing.JFrame {

    /**
     * Creates new form AudioSettings
     */
    public AudioSettings() {
        initComponents();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        audioSetInfoCheckbox = new javax.swing.JCheckBox();
        audioSetSpokenTestButton = new javax.swing.JButton();
        audioSetSpokenVolSlider = new javax.swing.JSlider();
        audioSetEnvironmentCheckBox = new javax.swing.JCheckBox();
        audioSetEnvVolSlider = new javax.swing.JSlider();
        audioSetEnvTestButton = new javax.swing.JButton();
        audioSetSelfTestButton = new javax.swing.JButton();
        audioSetSelfVolSlider = new javax.swing.JSlider();
        audioSetSelfCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ttsComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        audioSetTTSTestButton = new javax.swing.JButton();
        audioSetTTSReplaceCheckBox = new javax.swing.JCheckBox();
        audioSaveCloseButton = new javax.swing.JButton();
        audioSettingsSaveButton = new javax.swing.JButton();
        audioSettingsCancelButton = new javax.swing.JButton();

        jButton6.setText("Save and Close");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        audioSetInfoCheckbox.setSelected(true);
        audioSetInfoCheckbox.setText("Spoken Information");
        audioSetInfoCheckbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSetInfoCheckboxActionPerformed(evt);
            }
        });

        audioSetSpokenTestButton.setText("Test");
        audioSetSpokenTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSetSpokenTestButtonActionPerformed(evt);
            }
        });

        audioSetSpokenVolSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                audioSetSpokenVolSliderStateChanged(evt);
            }
        });
        audioSetSpokenVolSlider.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                audioSetSpokenVolSliderPropertyChange(evt);
            }
        });

        audioSetEnvironmentCheckBox.setSelected(true);
        audioSetEnvironmentCheckBox.setText("Environment");
        audioSetEnvironmentCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSetEnvironmentCheckBoxActionPerformed(evt);
            }
        });

        audioSetEnvVolSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                audioSetEnvVolSliderStateChanged(evt);
            }
        });

        audioSetEnvTestButton.setText("Test");
        audioSetEnvTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSetEnvTestButtonActionPerformed(evt);
            }
        });

        audioSetSelfTestButton.setText("Test");
        audioSetSelfTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSetSelfTestButtonActionPerformed(evt);
            }
        });

        audioSetSelfVolSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                audioSetSelfVolSliderStateChanged(evt);
            }
        });

        audioSetSelfCheckBox.setText("Self-produced");

        jLabel1.setText("Sounds to use:");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Volume-Booster-20x20.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Volume-Booster-20x20.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Volume-Booster-20x20.png"))); // NOI18N

        ttsComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ttsComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttsComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Text-to-Speech (TTS) Voice");

        audioSetTTSTestButton.setText("Test");
        audioSetTTSTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSetTTSTestButtonActionPerformed(evt);
            }
        });

        audioSetTTSReplaceCheckBox.setText("Replace TTS with high-quality recordings when available");
        audioSetTTSReplaceCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSetTTSReplaceCheckBoxActionPerformed(evt);
            }
        });

        audioSaveCloseButton.setText("Save and Close");
        audioSaveCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSaveCloseButtonActionPerformed(evt);
            }
        });

        audioSettingsSaveButton.setText("Save");
        audioSettingsSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSettingsSaveButtonActionPerformed(evt);
            }
        });

        audioSettingsCancelButton.setText("Cancel");
        audioSettingsCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audioSettingsCancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(audioSetInfoCheckbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(audioSetEnvironmentCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(audioSetSelfCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(audioSetSelfVolSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(audioSetSelfTestButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(audioSetEnvVolSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(audioSetEnvTestButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(audioSetSpokenVolSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(audioSetSpokenTestButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(audioSaveCloseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioSettingsSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(audioSettingsCancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(ttsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(audioSetTTSReplaceCheckBox)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(audioSetTTSTestButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(audioSetSpokenVolSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(audioSetSpokenTestButton)
                        .addComponent(audioSetInfoCheckbox)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(audioSetEnvVolSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(audioSetEnvTestButton)
                        .addComponent(audioSetEnvironmentCheckBox))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(audioSetSelfVolSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(audioSetSelfTestButton)
                        .addComponent(audioSetSelfCheckBox))
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ttsComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(audioSetTTSTestButton)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(audioSetTTSReplaceCheckBox)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(audioSaveCloseButton)
                    .addComponent(audioSettingsSaveButton)
                    .addComponent(audioSettingsCancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void audioSetEnvironmentCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSetEnvironmentCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetEnvironmentCheckBoxActionPerformed

    private void audioSetInfoCheckboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSetInfoCheckboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetInfoCheckboxActionPerformed

    private void audioSetTTSReplaceCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSetTTSReplaceCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetTTSReplaceCheckBoxActionPerformed

    private void ttsComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttsComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ttsComboBoxActionPerformed

    private void audioSetSelfVolSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_audioSetSelfVolSliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetSelfVolSliderStateChanged

    private void audioSetEnvVolSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_audioSetEnvVolSliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetEnvVolSliderStateChanged

    private void audioSetSpokenVolSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_audioSetSpokenVolSliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetSpokenVolSliderStateChanged

    private void audioSaveCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSaveCloseButtonActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Audio settings action performed: save & close");
        this.setVisible(false);
        //this.dispose();
    }//GEN-LAST:event_audioSaveCloseButtonActionPerformed

    private void audioSettingsSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSettingsSaveButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Audio settings action performed: save");
     
    }//GEN-LAST:event_audioSettingsSaveButtonActionPerformed

    private void audioSettingsCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSettingsCancelButtonActionPerformed
        // TODO add your handling code here:
        System.out.println("Audio settings action performed: cancel");
        //this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING)); //mimic pressing 'x' box on window
        this.setVisible(false);
        //this.dispose();
    }//GEN-LAST:event_audioSettingsCancelButtonActionPerformed

    private void audioSetSpokenTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSetSpokenTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetSpokenTestButtonActionPerformed

    private void audioSetEnvTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSetEnvTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetEnvTestButtonActionPerformed

    private void audioSetSelfTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSetSelfTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetSelfTestButtonActionPerformed

    private void audioSetTTSTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audioSetTTSTestButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetTTSTestButtonActionPerformed

    private void audioSetSpokenVolSliderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_audioSetSpokenVolSliderPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_audioSetSpokenVolSliderPropertyChange

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton audioSaveCloseButton;
    private javax.swing.JButton audioSetEnvTestButton;
    private javax.swing.JSlider audioSetEnvVolSlider;
    private javax.swing.JCheckBox audioSetEnvironmentCheckBox;
    private javax.swing.JCheckBox audioSetInfoCheckbox;
    private javax.swing.JCheckBox audioSetSelfCheckBox;
    private javax.swing.JButton audioSetSelfTestButton;
    private javax.swing.JSlider audioSetSelfVolSlider;
    private javax.swing.JButton audioSetSpokenTestButton;
    private javax.swing.JSlider audioSetSpokenVolSlider;
    private javax.swing.JCheckBox audioSetTTSReplaceCheckBox;
    private javax.swing.JButton audioSetTTSTestButton;
    private javax.swing.JButton audioSettingsCancelButton;
    private javax.swing.JButton audioSettingsSaveButton;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox ttsComboBox;
    // End of variables declaration//GEN-END:variables
}
