/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package audioTactileMap;

/**
 *
 * @author Administrator
 */
public class FindZonesSettings extends javax.swing.JFrame {

    /**
     * Creates new form FindZonesSettings
     */
    public FindZonesSettings() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findZonesSaveCloseButton = new javax.swing.JButton();
        findZonesSaveButton = new javax.swing.JButton();
        findZonesCancelButton = new javax.swing.JButton();
        findZonesProgressBar = new javax.swing.JProgressBar();
        findZonesFindNowButton = new javax.swing.JButton();
        minZoneSizeSlider = new javax.swing.JSlider();
        maxZoneSizeSlider = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        findZonesSaveCloseButton.setText("Save and Close");
        findZonesSaveCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findZonesSaveCloseButtonActionPerformed(evt);
            }
        });

        findZonesSaveButton.setText("Save");
        findZonesSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findZonesSaveButtonActionPerformed(evt);
            }
        });

        findZonesCancelButton.setText("Cancel");
        findZonesCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findZonesCancelButtonActionPerformed(evt);
            }
        });

        findZonesFindNowButton.setText("Find Now");

        minZoneSizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                minZoneSizeSliderStateChanged(evt);
            }
        });

        maxZoneSizeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                maxZoneSizeSliderStateChanged(evt);
            }
        });

        jLabel1.setText("Minimum Zone Size");

        jLabel2.setText("Maximum Zone Size");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minZoneSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(findZonesSaveCloseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findZonesSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(findZonesCancelButton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(findZonesFindNowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maxZoneSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(findZonesProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minZoneSizeSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maxZoneSizeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(findZonesFindNowButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(findZonesProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findZonesSaveCloseButton)
                    .addComponent(findZonesSaveButton)
                    .addComponent(findZonesCancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minZoneSizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_minZoneSizeSliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_minZoneSizeSliderStateChanged

    private void maxZoneSizeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_maxZoneSizeSliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_maxZoneSizeSliderStateChanged

    private void findZonesSaveCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findZonesSaveCloseButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findZonesSaveCloseButtonActionPerformed

    private void findZonesSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findZonesSaveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findZonesSaveButtonActionPerformed

    private void findZonesCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findZonesCancelButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findZonesCancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findZonesCancelButton;
    private javax.swing.JButton findZonesFindNowButton;
    private javax.swing.JProgressBar findZonesProgressBar;
    private javax.swing.JButton findZonesSaveButton;
    private javax.swing.JButton findZonesSaveCloseButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSlider maxZoneSizeSlider;
    private javax.swing.JSlider minZoneSizeSlider;
    // End of variables declaration//GEN-END:variables
}
